# Generated by Django 4.2 on 2024-06-28 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_id', models.CharField(max_length=1)),
                ('choice_text', models.CharField(max_length=300)),
                ('value1', models.SmallIntegerField(default=0)),
                ('value2', models.SmallIntegerField(default=0)),
                ('value3', models.SmallIntegerField(default=0)),
                ('value4', models.SmallIntegerField(default=0)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoQuestions.question')),
            ],
        ),
    ]
